### ISSUE TITLE
Any volunteer to make new repo with all merges?

### ISSUE THREAD

**Issue by timofonic** [sjl/learnvimscriptthehardway#100]
Hello to...

@AlexRiina @colwem @cosinequanon @dahn-d @drio @eduOS @hk3380 @hydRAnger @madgen @marlun @markmontymark @mjperrone @mskadu @nicoder @nielsbom @nikkypx @nkalvi @jfmercer @kyptin @rhilenova @roryokane @tapichu @xavierchow

Since @sjl seems to have abandoned this project. Any hopes some of the latest contributors nimight merge them in some of your repositories?

I'm trying to get used to NeoVim, but I miss resources like this. Any hopes?

If there's volunteers doing it, maybe it will be interesting to spread the word in the NeoVim and Vim communities :D 

Kind regards.

**Comment by mskadu** [comment]
I don't mind giving it a go unless someone else has already started?

**Comment by rhilenova** [comment]
Has anyone tried emailing him directly?

**Comment by mskadu** [comment]
I've made a start and have also just dropped him a note. I will let you know what happens.

**Comment by mskadu** [comment]
No response yet - I have sent him a follow-up. I checked his Google+ page and that's not been updated for the same sort of period.

Interestingly enough, I came across [this article](https://www.wired.com/2013/12/forked/) which led me to the [Forked project](https://github.com/ys/forked) by @ys - a tool to find active forks for abandoned projects.  Which in turn led me to a [chinese fork](https://github.com/isayme/learnvimscriptthehardway-cn)  - hey @isayme :)

In the meanwhile, can I please request you good folks to start contributing over at [mine](https://github.com/mskadu/learnvimscriptthehardway)?

**Comment by sjl** [comment]
Hello.

I have not had time to work on this for a while.  That doesn't mean you can ignore the copyright and just take it and do what you want with it.  The front page of the site says:

> The book is copyright 2013 by Steve Losh, all rights reserved. You can redistribute it **as long as you don't make any changes** and don't charge for it.

Yes it sucks that I'm busy/lazy and haven't merged things.  Sorry.  Maybe I'll get around to it some day.  But the copyright is still mine.

I realize that technically even making a github repo for the purposes of opening a PR is "redistributing with changes".  I obviously don't have a problem with that.  But if you're going to just fork the book and try to make a new "canonical" repo for it then that's bad.  I know, I suck, I'm a terrible person, etc etc.  If you want something more up to date you'll need to write your own book.

**Comment by mskadu** [comment]
Hey there, welcome back. 

And **no**, I am not after claiming your changes as mine 👎 If I was, I wouldn't have asked/ emailed you would i?

If you have noticed my fork, there are ZERO changes to your own text - especially copyright claims. As a matter of fact, other than the forked github URL (which gets auto-generated by github) I have nothing specific to me in there. In case you have not noticed yet - Any fixes (not changes) I have made have also been PR-ed over to your master.

I have been a Vim user (and fan!) for over one and a half decade. I have zero interest in making money out of this, and ALL the interest in keeping the content updated for others to learn Vimscript.

So a "_thank you_", to begin with would have been nice. 

PS: I will stop updating my fork when when you start processing your push requests.

**Comment by madgen** [comment]
@mskadu: @sjl is right. There is no need to be hostile and you should respect his wishes.

That said 🍿🍿🍿.

**Comment by mskadu** [comment]
That doesn't mean I am wrong ;-) And I don't think I was being hostile. 

I am merely pointing out, that had @sjl looked - he would have noticed that I am doing his work and giving him all the due credit. 

And nothing I have written above or anywhere else should have given him reason to believe I was encroaching on his copyright. If he can show me something that did - I will not hesitate to apologise.  

I've always believed that when dealing with the kindness of strangers, the least one can offer in return is politeness if not thanks. 

Need I point out that I did not end with a "_go to hell_" (which I had every right to). My only intention remains to help others learn.

**Comment by isayme** [comment]
add a collaborator to this project would be great.

**Comment by sjl** [comment]
> I am not after claiming your changes as mine

I never said this.  I don't even know what this means.  I *haven't made* any changes -- this is why people are salty.

Are you saying you're not claiming my *text* as yours?  That's true, but the copyright doesn't say "you can redistribute and change it as long as you give me credit" it says "you can redistribute it **if you don't make any changes**".

Again: I've not really cared about people "redistributing" to open PRs, even though this is *technically* against the "license".  But when someone comes in and says "you're not merging things, and I want you to merge things, so I'm gonna take over stewardship of your book now" I start to care.

Yes, it sucks that I'm busy and lazy.  But putting something on GitHub doesn't mean I'm obligated to process pull requests in a timely fashion, or at all.

In hindsight I probably shouldn't have made this repo public to begin with, since I don't have time to deal with PRs and "on GitHub" often implies "free to do with as you wish".  That would have headed everything off at the pass.

I'm gonna lock this now so we can all save our popcorn for the US election cycle.
