### ISSUE TITLE
Typo in chapter 27

### ISSUE THREAD

**Issue by joshgummersall** [sjl/learnvimscriptthehardway#86]
In the last paragraph in [the section on Lower and Upper Case](https://github.com/sjl/learnvimscriptthehardway/blob/master/chapters/27.markdown#lower-and-upper-case) the text reads:

> It's up to you to decide whether to use `tolower` and `==#`, or just `==?` to perform case-sensitive comparisons.

It should read:

> It's up to you to decide whether to use `tolower` and `==#`, or just `==?` to perform **case-insensitive** comparisons.

**Comment by mskadu** [comment]
Hey there. This has been fixed in my fork of this project at:

https://github.com/mskadu/learnvimscriptthehardway/commit/5eeaf3b11d2e3944517d2ee66804329f71e7ef63#diff-bc366947ffb559d5c43111496b9ab6d0

Hopefully, if/when @sjl does revive this project - I can merge all such fixes back into this project ;-)

Thank you for reporting this issue. Perhaps you will consider doing so in the revived fork?
